apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service-api
  namespace: books-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-service-api
  template:
    metadata:
      labels:
        app: books-service-api
    spec:
      containers:
        - name: books-service-api
          image: wikator/books-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
