apiVersion: v1
kind: Service
metadata:
  name: books-service-api
  namespace: books-platform
spec:
  selector:
    app: books-service-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort