apiVersion: v1
kind: Service
metadata:
  name: orders-service-api
  namespace: books-platform
spec:
  selector:
    app: orders-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31001
  type: NodePort
