apiVersion: v1
kind: Service
metadata:
  name: books-frontend
  namespace: books-platform
spec:
  selector:
    app: books-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31002
  type: NodePort