apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-notifications-init-config
  namespace: books-platform
data:
  init-mongo.js: |
    db = db.getSiblingDB('BookStore');
    db.createCollection('Books');
  