apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-notifications
  namespace: books-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-notifications
  template:
    metadata:
      labels:
        app: mongodb-notifications
    spec:
      containers:
        - name: mongodb-notifications
          image: mongo
          ports:
            - containerPort: 27017
      volumes:
        - name: init-script
          configMap:
            name: mongo-init-config
