apiVersion: v1
kind: Service
metadata:
  name: notification-service-api
  namespace: books-platform
spec:
  selector:
    app: notification-service-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003
  type: NodePort